### ISSUE TITLE
header scrunches on member search

### ISSUE THREAD

**Issue by polarbeardesign** [polarbeardesign/caf_app#1]
After performing a user search, the header goes into scroll mode (sort of)

**Comment by johnivanoff** [comment]
How do you **member search**?

**Comment by johnivanoff** [comment]
got it

**Comment by johnivanoff** [comment]
I first noticed that the `#top_2` div height was getting set and searched to find that. Since it was an _inline_ style, I figured [JS was writing it](https://github.com/polarbeardesign/caf_app/blob/5fd7b98ae7659349874021f5a7257e2251fe6761/app/assets/javascripts/jquery.sticky.js#L104)
<img width="918" alt="screenshot 2018-08-27 at 10 06 20 pm" src="https://user-images.githubusercontent.com/8841/44700318-79ab9f00-aa56-11e8-826d-ec281e02a7be.png">
When you change _search_ to _searched_ the height was back to `78px`, but it was like the next `div` had no height.
<img width="918" alt="screen shot 2018-08-27 at 10 06 49 pm" src="https://user-images.githubusercontent.com/8841/44700362-bbd4e080-aa56-11e8-938e-fe64dfacbce9.png">

This is what finally tipped me off. 
<img width="899" alt="screenshot 2018-08-27 at 11 23 08 pm" src="https://user-images.githubusercontent.com/8841/44700166-da86a780-aa55-11e8-8c77-7126f279acb6.png">
digging further I realize there is no unordered list for the main menu
When I dug into what made the [main menu](https://github.com/polarbeardesign/caf_app/blob/master/app/controllers/application_controller.rb#L22) I realized what the problem was. I changed the name of the member search box to `q` so there wouldn't be any more confusion for rails

**Comment by polarbeardesign** [comment]
Looks good - thanks
